name: Lostshard
main: com.lostshard.lostshard.Main.Lostshard
version: 0.01
commands:
   plot:
      description: Plot commands.
      usage: /<command> (subCommand)
   bank:
      description: Access your bank inventory at the local bank.
      usage: /<command>
   tradegold:
      description: trade 1 gold ingot to 100gc at a bank.
      usage: /<command> (amount)
   pay:
      description: pay player money.
      usage: /<command> (player) (amount)
   claim:
      description: claim capturepoint.
      usage: /<command>
   capturepoints:
      description: get a list of all capturepoints.
      usage: /<command>
      