name: Lostshard
main: com.lostshard.lostshard.Main.Main
version: 0.01
commands:
   plot:
      Plot commands.
      usage: /<command> (subCommand)
   bank:
      Access your bank inventory at the local bank.
      usage: /<command>
   tradegold:
      trade 1 gold ingot to 100gc at a bank.
      usage: /<command> (amount)
   pay:
      pay player money.
      usage: /<command> (player) (amount)
   claim:
      trade 1 gold ingot to 100gc at a bank.
      usage: /<command>
   capturepoints:
      trade 1 gold ingot to 100gc at a bank.
      usage: /<command>
      