name: Lostshard
main: com.lostshard.lostshard.Main.Lostshard
version: 0.01
commands:
   bank:
      description: Access your bank inventory at the local bank.
      usage: /<command>
   tradegold:
      description: trade 1 gold ingot to 100gc at a bank.
      usage: /<command> (amount)
   pay:
      description: pay a player money.
      usage: /<command> (player) (amount)
   plot:
      description: Plot commands.
      usage: /<command> (subCommand)
   claim:
      description: Claim a capturepoint.
      usage: /<command>
   capturepoints:
      description: Get a list of all capturepoints and position.
      usage: /<command>
   global:
      description: Selects the global chat.
      aliases: [g]
      usage: /<command>
   shout:
      description: Selects the shout chat.
      aliases: [s]
      usage: /<command>
   local:
      description: Selects the local chat.
      aliases: [l]
      usage: /<command>
   whisper:
      description: Selects the whisper chat.
      aliases: [w]
      usage: /<command>
   msg:
      description: Send a private message to a player.
      aliases: [m]
      usage: /<command> (Player)
   toggleglobalchat:
      description: Toggle global chat.
      aliases: [toggleglobal]
      usage: /<command>
   toggleprivatechat:
      description: Toggle private chat.
      aliases: [togglemsg,togglemsgchat]
      usage: /<command>
   replay:
      description: Replay on a private message.
      aliases: [r]
      usage: /<command> (Player)
   stats:
      description: Output player stats.
      usage: /<command>
   who:
      description: Output player list.
      usage: /<command>
   whois:
      description: Output whois.
      usage: /<command>
   spawn:
      description: Teleports to town after 10sec have a 3 houre .
      usage: /<command>
   resetspawn:
      description: Output whois.
      usage: /<command>
   rules:
      description: Output whois.
      aliases: [modt]
      usage: /<command>