name: Lostshard
main: com.lostshard.lostshard.Main.Lostshard
version: 0.01
commands:
   bank:
      description: Access your bank inventory at the local bank.
      usage: /<command>
   tradegold:
      description: trade 1 gold ingot to 100gc at a bank.
      usage: /<command> (amount)
   pay:
      description: pay player money.
      usage: /<command> (player) (amount)
   plot:
      description: Plot commands.
      usage: /<command> (subCommand)
   claim:
      description: claim capturepoint.
      usage: /<command>
   capturepoints:
      description: get a list of all capturepoints.
      usage: /<command>
   global:
      description: Toggle global chat.
      usage: /<command>
   shout:
      description: Toggle shout chat.
      usage: /<command>
   local:
      description: Toggle local chat.
      usage: /<command>
   whisper:
      description: Toggle whisper chat.
      usage: /<command>
   msg:
      description: Message a private message to player.
      usage: /<command> (Player)
   stats:
      description: Output player stats.
      usage: /<command>
   who:
      description: Output player list.
      usage: /<command>
   whois:
      description: Output whois.
      usage: /<command>
   spawn:
      description: Output whois.
      usage: /<command>
   resetspawn:
      description: Output whois.
      usage: /<command>
   rules:
      description: Output whois.
      usage: /<command>